export const majorTags = [
  "implementation",
  "dp",
  "graphs",
  "data_structures",
  "string",
  "greedy",
  "bruteforcing",
  "graph_traversal",
  "sorting",
  "trees",
  "binary_search",
  "bfs",
  "simulation",
  "dfs",
  "bitmask",
  "backtracking",
  "divide_and_conquer",
  "priority_queue",
  "stack",
  "two_pointer",
  "mst",
  "knapsack",
  "recursion",
  "topological_sorting",
  "deque",
  "queue",
  "bellman_ford",
  "dijkstra",
  "prefix_sum",
  "disjoint_set",
  "hash_set",
  "tree_set",
];

export const levels = [
  { num: 6, tier: "Silver 5" },
  { num: 7, tier: "Silver 4" },
  { num: 8, tier: "Silver 3" },
  { num: 9, tier: "Silver 2" },
  { num: 10, tier: "Silver 1" },
  { num: 11, tier: "Gold 5" },
  { num: 12, tier: "Gold 4" },
  { num: 13, tier: "Gold 3" },
  { num: 14, tier: "Gold 2" },
  { num: 15, tier: "Gold 1" },
  { num: 16, tier: "Platinum 5" },
  { num: 17, tier: "Platinum 4" },
  { num: 18, tier: "Platinum 3" },
  { num: 19, tier: "Platinum 2" },
  { num: 20, tier: "Platinum 1" },
];

export const Options = {
  tagOption: {
    method: "GET",
    url: "https://solved.ac/api/v3/tag/list",
    headers: { "Content-Type": "application/json" },
  },
  baseSearchProblemOption: {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "" },
    headers: { "Content-Type": "application/json" },
  },
  totalProblemOption: {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: `*s5..p1&lang:ko&solvable:true` },
    headers: { "Content-Type": "application/json" },
  },
};
