export const taglistOptions = {
  method: "GET",
  url: "https://solved.ac/api/v3/tag/list",
  headers: { "Content-Type": "application/json" },
};

export const silverOptions = [
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "1" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "2" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "3" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "4" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "5" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "6" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "7" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "8" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "9" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "10" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "11" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "12" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "13" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "14" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*s1..s5&lang:ko&s#100..", page: "15" },
    headers: { "Content-Type": "application/json" },
  },
];

export const goldOptions = [
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "1" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "2" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "3" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "4" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "5" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "6" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "7" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "8" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "9" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "10" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "11" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*g1..g5&lang:ko&s#150..", page: "12" },
    headers: { "Content-Type": "application/json" },
  },
];

export const platinumOptions = [
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*p1..p5&lang:ko&s#100..", page: "1" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*p1..p5&lang:ko&s#100..", page: "2" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*p1..p5&lang:ko&s#100..", page: "3" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*p1..p5&lang:ko&s#100..", page: "4" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*p1..p5&lang:ko&s#100..", page: "5" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*p1..p5&lang:ko&s#100..", page: "6" },
    headers: { "Content-Type": "application/json" },
  },
  {
    method: "GET",
    url: "https://solved.ac/api/v3/search/problem",
    params: { query: "*p1..p5&lang:ko&s#100..", page: "7" },
    headers: { "Content-Type": "application/json" },
  },
];

export const majorTags = [
  "implementation",
  "dp",
  "graphs",
  "data_structures",
  "string",
  "greedy",
  "bruteforcing",
  "graph_traversal",
  "sorting",
  "trees",
  "binary_search",
  "bfs",
  "simulation",
  "dfs",
  "bitmask",
  "backtracking",
  "divide_and_conquer",
  "priority_queue",
  "stack",
  "two_pointer",
  "mst",
  "knapsack",
  "recursion",
  "hashing",
  "topological_sorting",
  "deque",
  "queue",
  "bellman_ford",
  "dijkstra",
  "prefix_sum",
  "disjoint_set",
];

export const levels = [
  { num: 6, tier: "Silver 5" },
  { num: 7, tier: "Silver 4" },
  { num: 8, tier: "Silver 3" },
  { num: 9, tier: "Silver 2" },
  { num: 10, tier: "Silver 1" },
  { num: 11, tier: "Gold 5" },
  { num: 12, tier: "Gold 4" },
  { num: 13, tier: "Gold 3" },
  { num: 14, tier: "Gold 2" },
  { num: 15, tier: "Gold 1" },
  { num: 16, tier: "Platinum 5" },
  { num: 17, tier: "Platinum 4" },
  { num: 18, tier: "Platinum 3" },
  { num: 19, tier: "Platinum 2" },
  { num: 20, tier: "Platinum 1" },
];
